### ISSUE TITLE
MagIC GUI test failure

### ISSUE THREAD

**Issue by Caoimhinmg** [Caoimhinmg/PmagPy#7]
Just tried the testing bash script again and I'm getting the segmentation error on a MagIC GUI test with this error:

```bash
running pmagpy_tests.test_magic_gui
/usr/local/lib/python3.4/dist-packages/matplotlib/__init__.py:1401: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
.......Traceback (most recent call last):
  File "/home/kevin/Code/Paleomag/KevinPmagPy/programs/magic_gui.py", line 279, in make_grid_frame
    wx.Yield()
wx._core.wxAssertionError: C++ assertion "source" failed at /tmp/pip-build-fae30yho/wx/ext/wxWidgets/src/gtk/window.cpp(3213) in DoScreenToClient(): ScreenToClient failed on unrealized window
F..
======================================================================
FAIL: test_sample_button (pmagpy_tests.test_magic_gui.TestMainFrame)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kevin/Code/Paleomag/KevinPmagPy/pmagpy_tests/test_magic_gui.py", line 62, in test_sample_button
    self.assertTrue(window, 'samples grid window was not created')
AssertionError: None is not true : samples grid window was not created
```

No idea how if this is serious or not, but I have no idea how to fix this. Any ideas @moonshoes87

**Comment by moonshoes87** [comment]
Hmmm, I can run all Magic GUI tests with no problem (with syntax: `pythonw -m unittest pmagpy_tests.test_magic_gui`)

When I run tests with the run_all_tests script, it hangs on one of the test_dialog_components tests (a test that runs fine by itself).  

I really don't know why the tests are so weird in combination, but behaving just fine when run one module at a time.  I'm not sure how much we want to prioritize this, as it seems to be an unpredictably moving target, for some reason.

**Comment by Caoimhinmg** [comment]
Yeah this seems ridiculously unpredictable. For now I'll just close this issue as this error seems to only occur occasionally the last time I ran `python3 -m unittests pmagpy_tests.test_magic_gui` it worked fine and so did ./run_all_tests.sh
