### ISSUE TITLE
distributing via pip 

### ISSUE THREAD

**Issue by moonshoes87** [Caoimhinmg/PmagPy#9]
It looks like we may be able to distribute smartly via pip, using wheels.

We can make a python 3 wheel and a python 2 wheel with the same version number, and pip will grab the right version.  I think we will still want to create an sdist, which we will have to choose to do as python 3 or python 2.  I'm not sure exactly when that would be used as a fallback, since pip prefers wheels when available.  I tested this on OS X and Windows 10, and both correctly grabbed the relevant wheel.  @Caoimhinmg, can you test this on Linux?  You will need to download from test PyPI:

    pip install -i https://testpypi.python.org/pypi pmagpy --upgrade --no-deps --force-reinstall --no-cache-dir

And same for pmagpy-cli.  If you can try this with both Python 2 and Python 3, and make sure you get the right wheel, that would be awesome.

This is a great article for how to supportively stop supporting python 2:  http://www.python3statement.org/practicalities/.  This addresses a bunch of the pip issues, and I am working my way through it.  

(my husband is also a developer and really wanted me to include a gif, so:)
![awesome](https://media3.giphy.com/media/l2Sqir5ZxfoS27EvS/200w.gif#3-grid1)

**Comment by Caoimhinmg** [comment]
Hey @moonshoes87, just gave it a shot and pmagpy installed fine in python2 and 3, but pmagpy-cli gave me this:

```
Could not find a version that satisfies the requirement pmagpy-cli (from versions: )
No matching distribution found for pmagpy-cli
```

for python2, however, it worked fine in python3.

**Comment by moonshoes87** [comment]
Oops.  Yeah, that makes sense -- I forgot that I was still actively mucking around with test PyPI, which only stores the most recent version you upload, and there was probably no python 2 wheel available when you tried to test it.  I might ask you to re-try that test eventually.
